ember:
  image: danlynn/ember-cli:0.2.7
  ports:
   - "80:4200"
   - "35729:35729"
  volumes:
   - .:/tmp/project
  entrypoint:
   - sh
  command: -c "tar -xmf /tmp/project/tmp/init.tar && npm install && bower install --allow-root && ember server"
